# Generated by Django 5.0.3 on 2024-04-07 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_pdf_bibliografia_pdf_contenido_pdf_evaluacion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pdf',
            old_name='metodlogia',
            new_name='metodologia',
        ),
    ]
