# Generated by Django 5.0.3 on 2024-04-08 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_pdf_bibliografia_alter_pdf_contenido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdf',
            name='Carga_Horaria_Semanal',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pdf',
            name='Carga_Horaria_Semestral',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pdf',
            name='Profesor',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pdf',
            name='Requisitos',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pdf',
            name='condicion',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='pdf',
            name='curso',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pdf',
            name='semestre',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
