# Generated by Django 5.0.3 on 2024-04-09 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_pdf_carga_horaria_semanal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf',
            name='Carga_Horaria_Semanal',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='Carga_Horaria_Semestral',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='Profesor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='Requisitos',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='bibliografia',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='condicion',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='contenido',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='curso',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='evaluacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='metodologia',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='objetivos',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='semestre',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
