# Generated by Django 5.0.3 on 2024-04-09 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_pdf_carga_horaria_semanal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf',
            name='Requisitos',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
