# Generated by Django 5.0.3 on 2024-04-09 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_pdf_requisitos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pdf',
            old_name='Requisitos',
            new_name='requisitos',
        ),
    ]
