# Generated by Django 5.0.3 on 2024-04-09 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_requisitos_pdf_requisitos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pdf',
            old_name='Carga_Horaria_Semanal',
            new_name='carga_Horaria_Semanal',
        ),
        migrations.RenameField(
            model_name='pdf',
            old_name='Carga_Horaria_Semestral',
            new_name='carga_Horaria_Semestral',
        ),
        migrations.RenameField(
            model_name='pdf',
            old_name='Profesor',
            new_name='profesor',
        ),
        migrations.AddField(
            model_name='pdf',
            name='fundamenttacion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
