# Generated by Django 5.0.3 on 2024-04-09 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_carga_horaria_semanal_pdf_carga_horaria_semanal_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pdf',
            old_name='fundamenttacion',
            new_name='fundamentacion',
        ),
    ]
